spring:
  profiles: dev
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: instructions-capture-service-dev
      auto-offset-reset: earliest
      enable.auto.commit: true
      properties:
        isolation.level: read_committed
    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true



management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,threaddump,httpexchanges

logging:
  level:
    root: DEBUG
    org.springframework: INFO
    org.apache.kafka: INFO
    com.example.instructions: DEBUG
