spring:
  profiles: dev
  server:
    port: 8080
    shutdown: graceful
    include-stacktrace: always
    include-message: always
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: instructions-capture-service-dev
      auto-offset-reset: earliest
      enable.auto.commit: true
      properties:
        isolation.level: read_committed
    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    streams:
      application-id: instructions-transformer   # REQUIRED
      properties:
        processing.guarantee: exactly_once_v2
        num.stream.threads: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,threaddump,httpexchanges

logging:
  level:
    root: DEBUG
    org.springframework: INFO
    org.apache.kafka: INFO
    com.example.instructions: DEBUG

app:
  kafka:
    topics:
      inbound: instructions.inbound
      outbound: instructions.outbound
  cache:
    ttl-ms: 600000                    # 10 minutes TTL for hot-window dedup
    max-entries: 250000               # soft cap; tune per memory budget
    hmac-secret: ${KEY_HASH_SECRET:dev-secret}