server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: instructions-capture-service
mvc:
  problemdetails:
    enabled: true
servlet:
  multipart:
    enabled: true
    max-file-size: 20MB
    max-request-size: 20MB
jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
app:
  kafka:
    topics:
      inbound: instructions.inbound
      outbound: instructions.outbound

  cache:
    ttl-ms: 600000                    # 10 minutes TTL for hot-window dedup
    max-entries: 250000               # soft cap; tune per memory budget
    hmac-secret: ${KEY_HASH_SECRET:dev-secret}